export type QuizOption = 1 | 2 | 3 | 4;
export type QuizDifficulty = "facile" | "medio" | "difficile";

export interface PythonQuestion {
  id: string;
  prompt: string;
  options: readonly [string, string, string, string];
  correctOption: QuizOption;
  difficulty: QuizDifficulty;
}

function question(id: number, prompt: string, options: [string, string, string, string], correctOption: QuizOption, difficulty: QuizDifficulty): PythonQuestion {
  return { id: `python-${id}`, prompt, options, correctOption, difficulty };
}

/** Versioned, bundled question data so the OBS overlay has no runtime database dependency. */
export const pythonQuestionBank: readonly PythonQuestion[] = [
  question(1, "Cosa restituisce len([1, 2, 3])?", ["2", "3", "4", "Un errore"], 2, "facile"),
  question(2, "Quale parola chiave definisce una funzione?", ["func", "def", "function", "lambda"], 2, "facile"),
  question(3, "Qual è il risultato di 7 // 2?", ["3", "3.5", "4", "Un errore"], 1, "facile"),
  question(4, "Quale collezione mantiene l'ordine di inserimento e ammette duplicati?", ["set", "dict", "list", "frozenset"], 3, "medio"),
  question(5, "A cosa equivale bool([])?", ["True", "False", "None", "Un errore"], 2, "facile"),
  question(6, "Quale sintassi crea una tupla con un solo elemento?", ["(1)", "[1]", "{1}", "(1,)"], 4, "difficile"),
  question(7, "Qual è il risultato di 'Python'[1:4]?", ["Pyt", "yth", "tho", "ython"], 2, "medio"),
  question(8, "Quale operatore verifica l'identità di un oggetto?", ["==", "=", "is", "in"], 3, "difficile"),
  question(9, "Cosa produce range(3) se iterato?", ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "Una sequenza infinita"], 2, "facile"),
  question(10, "Quale istruzione salta al resto dell'iterazione successiva del ciclo?", ["break", "continue", "pass", "return"], 2, "facile"),
  question(11, "Cosa restituisce {'a': 1}.get('b') di default?", ["0", "False", "None", "KeyError"], 3, "medio"),
  question(12, "Quale operazione aggiunge un elemento in fondo a una lista?", ["add", "append", "extend", "insert"], 2, "facile"),
  question(13, "Qual è il risultato di [1, 2] + [3]?", ["[1, 2, 3]", "[4, 5]", "[1, 2, [3]]", "TypeError"], 1, "facile"),
  question(14, "Quale built-in elimina i duplicati perdendo l'ordine?", ["list", "tuple", "set", "dict"], 3, "facile"),
  question(15, "Cosa restituisce '  ciao  '.strip()?", ["'  ciao  '", "'ciao'", "' ciao '", "['ciao']"], 2, "facile"),
  question(16, "Quale eccezione solleva int('boh')?", ["TypeError", "ValueError", "KeyError", "IndexError"], 2, "medio"),
  question(17, "Cosa produce enumerate(['a', 'b'])?", ["Solo i valori", "Solo gli indici", "Coppie indice-valore", "Un dizionario"], 3, "medio"),
  question(18, "Quale comprehension crea i quadrati da 0 a 3?", ["[x*x for x in range(4)]", "{x*x for x in range(4)}", "(x*x for x in range(4))", "[x for x*x in range(4)]"], 1, "medio"),
  question(19, "Quanto vale 2 ** 3?", ["5", "6", "8", "9"], 3, "facile"),
  question(20, "Quale parola chiave importa un modulo?", ["include", "require", "import", "using"], 3, "facile"),
  question(21, "Cosa restituisce list(range(1, 5, 2))?", ["[1, 2, 3, 4]", "[1, 3]", "[2, 4]", "[1, 3, 5]"], 2, "medio"),
  question(22, "Quale metodo aggiunge a una lista tutti gli elementi di un altro iterabile?", ["append", "extend", "push", "merge"], 2, "medio"),
  question(23, "Cosa espone dict.items()?", ["Solo le chiavi", "Solo i valori", "Coppie chiave-valore", "Le chiavi ordinate"], 3, "facile"),
  question(24, "Quale sintassi intercetta un ValueError?", ["catch ValueError", "except ValueError", "rescue ValueError", "handle ValueError"], 2, "facile"),
  question(25, "Cosa fa il blocco finally?", ["Viene eseguito solo in caso di errore", "Viene eseguito solo senza errori", "Viene eseguito sempre dopo il try", "Ripete il blocco try"], 3, "medio"),
  question(26, "Quale parola chiave crea una funzione anonima?", ["def", "lambda", "anon", "yield"], 2, "facile"),
  question(27, "Cosa restituisce sorted([3, 1, 2])?", ["[3, 1, 2]", "[1, 2, 3]", "None", "Un set"], 2, "facile"),
  question(28, "Quale funzione restituisce l'elemento più grande?", ["high", "top", "max", "largest"], 3, "facile"),
  question(29, "Cosa restituisce any([False, False, True])?", ["False", "True", "None", "ValueError"], 2, "medio"),
  question(30, "Cosa restituisce all([True, True, False])?", ["True", "False", "None", "ValueError"], 2, "medio"),
  question(31, "Quale sequenza built-in è immutabile?", ["list", "set", "tuple", "dict"], 3, "facile"),
  question(32, "Cosa seleziona l'indice negativo -1?", ["Il primo elemento", "Il secondo elemento", "L'ultimo elemento", "Un errore"], 3, "facile"),
  question(33, "Cosa restituisce 'a,b'.split(',')?", ["('a', 'b')", "['a', 'b']", "{'a', 'b'}", "'ab'"], 2, "facile"),
  question(34, "Quale f-string mostra il valore della variabile name?", ["f'name'", "f'{name}'", "'{name}'", "f'{{name}}'"], 2, "facile"),
  question(35, "Cosa restituisce type(None).__name__?", ["null", "None", "NoneType", "undefined"], 3, "difficile"),
  question(36, "Quale istruzione crea una classe?", ["object User:", "class User:", "new User:", "struct User:"], 2, "facile"),
  question(37, "Cosa rappresenta self in un metodo di istanza?", ["Una parola chiave obbligatoria", "La classe stessa", "L'istanza corrente", "Una variabile globale"], 3, "medio"),
  question(38, "Quale metodo speciale inizializza un'istanza?", ["__start__", "__new__", "__init__", "__build__"], 3, "medio"),
  question(39, "Cosa restituisce isinstance(True, int) in Python?", ["True", "False", "None", "TypeError"], 1, "difficile"),
  question(40, "Quale decoratore trasforma un metodo in un attributo calcolato in sola lettura?", ["@staticmethod", "@classmethod", "@property", "@cached"], 3, "difficile"),
  question(41, "Cosa usa una funzione generatore per produrre valori in modo pigro?", ["return", "yield", "await", "emit"], 2, "medio"),
  question(42, "Quale espressione crea un generator expression?", ["[x for x in data]", "{x for x in data}", "(x for x in data)", "{x: x for x in data}"], 3, "medio"),
  question(43, "Cosa succede quando un generatore è esaurito?", ["Riparte da capo", "Solleva StopIteration", "Restituisce sempre None", "Si autoelimina"], 2, "difficile"),
  question(44, "Quale parola chiave delega l'iterazione a un altro generatore?", ["yield from", "return from", "for yield", "delegate"], 1, "difficile"),
  question(45, "Cosa restituisce map(str, [1, 2])?", ["['1', '2'] subito", "Un iteratore che applica str", "Una tupla", "Un dizionario"], 2, "medio"),
  question(46, "Quale built-in filtra un iterabile secondo un predicato?", ["select", "filter", "where", "keep"], 2, "medio"),
  question(47, "Cosa produce zip([1, 2], ['a', 'b'])?", ["(1, 'a'), (2, 'b')", "[1, 'a', 2, 'b']", "Un dizionario", "Un set"], 1, "medio"),
  question(48, "Quale parola chiave esce da una funzione restituendo un valore?", ["break", "continue", "return", "yield"], 3, "facile"),
  question(49, "Cosa fa pass?", ["Salta un'iterazione del ciclo", "Solleva un'eccezione", "Funge da segnaposto senza effetto", "Interrompe il programma"], 3, "facile"),
  question(50, "Quale operatore verifica l'appartenenza?", ["is", "in", "has", "contains"], 2, "facile"),
  question(51, "Cosa fa x = [1, 2]; y = x; y.append(3) alla variabile x?", ["Resta [1, 2]", "Diventa [1, 2, 3]", "Solleva un errore", "Copia x"], 2, "difficile"),
  question(52, "Quale operazione su una lista rimuove e restituisce di default l'ultimo elemento?", ["remove", "delete", "pop", "clear"], 3, "medio"),
  question(53, "Cosa fa list.remove(valore)?", ["Rimuove per indice", "Rimuove la prima occorrenza del valore", "Rimuove tutte le occorrenze", "Restituisce una nuova lista"], 2, "medio"),
  question(54, "Quale operazione su un dizionario rimuove e restituisce in sicurezza una chiave?", ["take", "pop", "delete", "discard"], 2, "medio"),
  question(55, "Cosa fa set.discard(valore) se il valore non è presente?", ["Solleva KeyError", "Restituisce False", "Non fa nulla", "Aggiunge il valore"], 3, "difficile"),
  question(56, "Qual è il risultato di {1, 2} | {2, 3}?", ["{2}", "{1, 2, 3}", "{1, 3}", "TypeError"], 2, "medio"),
  question(57, "Qual è il risultato di {1, 2} & {2, 3}?", ["{1, 2, 3}", "{1, 3}", "{2}", "{}"], 3, "difficile"),
  question(58, "Quale modulo è la fonte convenzionale di numeri casuali?", ["math", "statistics", "random", "solo secrets"], 3, "facile"),
  question(59, "Quale modulo fornisce oggetti per i percorsi di file?", ["os.pathlib", "pathlib", "files", "fs"], 2, "medio"),
  question(60, "Cosa garantisce with open(percorso) as file?", ["Il file viene messo in cache", "Il file viene chiuso all'uscita", "Il file è scrivibile", "Il file è in formato JSON"], 2, "medio"),
  question(61, "Quale modalità di apertura aggiunge testo a un file esistente?", ["'r'", "'w'", "'a'", "'x'"], 3, "medio"),
  question(62, "Cosa fa json.loads(testo)?", ["Scrive JSON su disco", "Analizza (parsing) del testo JSON", "Carica un modulo Python", "Valida un URL"], 2, "medio"),
  question(63, "Quale modulo standard gestisce le espressioni regolari?", ["regex", "re", "pattern", "match"], 2, "facile"),
  question(64, "Cosa richiede re.fullmatch?", ["Una corrispondenza in una posizione qualsiasi", "Una corrispondenza all'inizio", "Che l'intera stringa corrisponda", "Una corrispondenza senza distinzione tra maiuscole e minuscole"], 3, "difficile"),
  question(65, "Quale collezione è più adatta per operazioni su una coda FIFO?", ["list", "tuple", "collections.deque", "set"], 3, "difficile"),
  question(66, "Cosa conta collections.Counter?", ["La memoria degli oggetti", "Le occorrenze di elementi hashable", "Le iterazioni dei cicli", "Il tempo di CPU"], 2, "medio"),
  question(67, "Quale strumento crea un ambiente virtuale?", ["pip env", "python -m venv", "python -m virtual", "venv install"], 2, "medio"),
  question(68, "A cosa serve principalmente pip?", ["Compilare Python", "Gestire i pacchetti", "Formattare il codice", "Eseguire i test"], 2, "facile"),
  question(69, "Quale comando esegue un modulo come script?", ["python --module nome", "python -m nome", "python module nome", "pip run nome"], 2, "medio"),
  question(70, "A cosa è uguale __name__ quando un file viene eseguito direttamente?", ["'main'", "'__main__'", "Il nome del file", "None"], 2, "medio"),
  question(71, "Quale istruzione rappresenta il normale ramo condizionale?", ["when", "if", "match", "guard"], 2, "facile"),
  question(72, "Cosa significa elif?", ["Fine dell'if", "Altrimenti se (else if)", "Errore nell'if", "Valuta la lista se"], 2, "facile"),
  question(73, "Quale ciclo si usa di solito per iterare un iterabile?", ["while", "for", "repeat", "each"], 2, "facile"),
  question(74, "Cosa fa break dentro un ciclo?", ["Lo riavvia", "Esce dal ciclo più interno", "Salta questa iterazione", "Mette in pausa per un input"], 2, "facile"),
  question(75, "Un ciclo while continua a eseguire finché la sua condizione è:", ["True", "False", "Entrambe", "Solo una volta"], 1, "facile"),
  question(76, "Quale confronto verifica l'uguaglianza di valore?", ["=", "==", "is", ":="], 2, "facile"),
  question(77, "Cosa significa !=?", ["Assegnazione", "Identità", "Diverso da", "Non appartiene a"], 3, "facile"),
  question(78, "Quale operatore esegue l'AND logico?", ["&&", "and", "solo &", "AND"], 2, "facile"),
  question(79, "Qual è il risultato di not True?", ["True", "False", "None", "0"], 2, "facile"),
  question(80, "Quale valore è falsy?", ["'0'", "[0]", "{}", "'False'"], 3, "medio"),
  question(81, "Cosa definisce un parametro di funzione con = 3?", ["Un parametro obbligatorio", "Un valore predefinito", "Un'annotazione di tipo", "Un campo di classe"], 2, "facile"),
  question(82, "Quale prefisso raccoglie gli argomenti posizionali extra?", ["**args", "*args", "&args", "args*"], 2, "medio"),
  question(83, "Quale prefisso raccoglie gli argomenti nominali (keyword) extra?", ["*kwargs", "**kwargs", "&kwargs", "kwargs**"], 2, "medio"),
  question(84, "Cos'è una docstring?", ["Un'eccezione a runtime", "Una stringa che documenta modulo, classe o funzione", "Un commento che inizia con #", "Una variabile tipizzata"], 2, "facile"),
  question(85, "Quale guida di stile è ampiamente usata per il codice Python?", ["PEP 8", "RFC 2616", "ECMAScript", "Solo POSIX"], 1, "facile"),
  question(86, "Quale sintassi annota x come intero?", ["int x", "x -> int", "x: int", "x = int"], 3, "medio"),
  question(87, "Cosa comunica Optional[str] in un'annotazione di tipo?", ["Una stringa obbligatoria", "Una stringa oppure None", "Una lista di stringhe", "Solo un valore letterale stringa"], 2, "difficile"),
  question(88, "Quale modulo supporta le coroutine asincrone?", ["threading", "asyncio", "multiprocessing", "queue"], 2, "medio"),
  question(89, "Quale parola chiave attende un awaitable nel codice asincrono?", ["yield", "await", "pause", "join"], 2, "medio"),
  question(90, "Cosa crea async def?", ["Una funzione sincrona", "Una funzione coroutine", "Solo un generatore", "Un metodo di classe"], 2, "difficile"),
  question(91, "Quale classe base di eccezione si dovrebbe di solito intercettare per errori ordinari?", ["BaseException", "Exception", "SystemExit", "KeyboardInterrupt"], 2, "difficile"),
  question(92, "Cosa fa raise ValueError('errore')?", ["Registra un avviso", "Crea e solleva un'eccezione", "Restituisce un valore", "Interrompe solo un ciclo"], 2, "facile"),
  question(93, "Quale espressione crea una copia superficiale (shallow) di una lista?", ["items", "items[:]", "items.copy is False", "list is items"], 2, "difficile"),
  question(94, "Qual è il rischio principale di un argomento predefinito mutabile?", ["È più lento", "Viene condiviso tra le chiamate", "Non può essere letto", "Forza una tupla"], 2, "difficile"),
  question(95, "Quale costrutto è preferibile per la pulizia (cleanup) attorno a una risorsa?", ["goto", "with", "switch", "global"], 2, "medio"),
  question(96, "Cosa fa assert condizione quando la condizione è falsa?", ["Restituisce False", "Solleva AssertionError", "Stampa un avviso", "Riprova"], 2, "medio"),
  question(97, "Quale built-in restituisce il numero di elementi in un contenitore?", ["count", "size", "len", "length"], 3, "facile"),
  question(98, "Cosa restituisce reversed([1, 2, 3])?", ["[3, 2, 1] immediatamente", "Un iteratore in ordine inverso", "Una lista ordinata", "Un set"], 2, "medio"),
  question(99, "Quale metodo di stringa può unire un iterabile in una stringa?", ["concat", "join", "merge", "format"], 2, "facile"),
  question(100, "Cosa restituisce '::'.join(['a', 'b'])?", ["'ab'", "'a::b'", "['a::b']", "TypeError"], 2, "medio"),
];
